/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avions;

import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author Moussa
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Mouvement
     */
    public Accueil() {
        
        // <editor-fold defaultstate="collapsed" desc="Interface de la fenetre">
         initComponents();
         this.setTitle("Menu principal");
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setSize(580,400);
         nomAdmin.setText("Administrateur ["+id.getNdc()+"]");
         nomAdmin.setHorizontalAlignment(SwingConstants.CENTER);
         nomAdmin.setForeground(new java.awt.Color(102, 0, 0));
         // </editor-fold>
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Groupe1 = new javax.swing.ButtonGroup();
        image = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        avionRet = new javax.swing.JLabel();
        Séparateur = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        tModele = new javax.swing.JLabel();
        tRetard = new javax.swing.JLabel();
        tAeroports = new javax.swing.JLabel();
        tRapport = new javax.swing.JLabel();
        choix1 = new javax.swing.JRadioButton();
        choix2 = new javax.swing.JRadioButton();
        choix3 = new javax.swing.JRadioButton();
        choix4 = new javax.swing.JRadioButton();
        trait = new javax.swing.JLabel();
        nomAdmin = new javax.swing.JLabel();
        Deconnexion = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();
        Continuer = new javax.swing.JButton();
        trait1 = new javax.swing.JLabel();
        cadre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo-avion.png")); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setText("Trip Report : Gestion des retards");
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 10, 420, 30));

        avionRet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avionRet.setText("Menu principal");
        getContentPane().add(avionRet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, 20));
        getContentPane().add(Séparateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        tModele.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tModele.setText("Gestion des pilotes / co-pilotes :");
        jPanel1.add(tModele);
        tModele.setBounds(10, 60, 210, 30);

        tRetard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tRetard.setText("Gestion des modèles d'avions :");
        jPanel1.add(tRetard);
        tRetard.setBounds(10, 100, 200, 40);

        tAeroports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tAeroports.setText("Gestion des retards d'avions  :");
        jPanel1.add(tAeroports);
        tAeroports.setBounds(10, 150, 200, 40);

        tRapport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tRapport.setText("Créer un rapport de retards :");
        jPanel1.add(tRapport);
        tRapport.setBounds(10, 200, 190, 40);

        Groupe1.add(choix1);
        choix1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        choix1.setSelected(true);
        choix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix1ActionPerformed(evt);
            }
        });
        jPanel1.add(choix1);
        choix1.setBounds(220, 50, 30, 50);

        Groupe1.add(choix2);
        choix2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        choix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix2ActionPerformed(evt);
            }
        });
        jPanel1.add(choix2);
        choix2.setBounds(220, 100, 30, 40);

        Groupe1.add(choix3);
        choix3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        choix3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix3ActionPerformed(evt);
            }
        });
        jPanel1.add(choix3);
        choix3.setBounds(220, 150, 30, 40);

        Groupe1.add(choix4);
        choix4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        choix4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix4ActionPerformed(evt);
            }
        });
        jPanel1.add(choix4);
        choix4.setBounds(220, 200, 30, 40);

        trait.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(trait);
        trait.setBounds(0, 42, 270, 2);

        nomAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(nomAdmin);
        nomAdmin.setBounds(50, 10, 160, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 250));

        Deconnexion.setText("Quitter");
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(Deconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 100, 30));

        image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\accueil.png")); // NOI18N
        getContentPane().add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 260, 210));

        Continuer.setText("Continuer");
        Continuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuerActionPerformed(evt);
            }
        });
        getContentPane().add(Continuer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 100, 30));

        trait1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(trait1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 288, 250, -1));

        cadre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 250, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
             
        // <editor-fold defaultstate="collapsed" desc="Retour à l'interface Admin">
             this.dispose();
             new Login().setVisible(true);
             // </editor-fold>
             
    }//GEN-LAST:event_DeconnexionActionPerformed

    private void ContinuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuerActionPerformed
            
        // <editor-fold defaultstate="collapsed" desc="Menu des fenetres">
            if (choix1.isSelected()) {
            new Pilotes().setVisible(true);
            this.dispose();
            }
            if (choix2.isSelected()) {
            new ModeleAvion().setVisible(true);
            this.dispose();
            }
            if (choix3.isSelected()) {
            new Mouvement().setVisible(true);
            this.dispose();
            }
            if (choix4.isSelected()) {
            new Rapport().setVisible(true);
            this.dispose();
            }
            // </editor-fold>
            
    }//GEN-LAST:event_ContinuerActionPerformed

    private void choix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix1ActionPerformed

    private void choix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix2ActionPerformed

    private void choix3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix3ActionPerformed

    private void choix4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continuer;
    private javax.swing.JButton Deconnexion;
    private javax.swing.ButtonGroup Groupe1;
    private javax.swing.JSeparator Séparateur;
    private javax.swing.JLabel avionRet;
    private javax.swing.JLabel cadre;
    private javax.swing.JRadioButton choix1;
    private javax.swing.JRadioButton choix2;
    private javax.swing.JRadioButton choix3;
    private javax.swing.JRadioButton choix4;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomAdmin;
    private javax.swing.JLabel tAeroports;
    private javax.swing.JLabel tModele;
    private javax.swing.JLabel tRapport;
    private javax.swing.JLabel tRetard;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel trait;
    private javax.swing.JLabel trait1;
    // End of variables declaration//GEN-END:variables
}
