package avions;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moussa
 */
public class Login extends javax.swing.JFrame {
     

    /**
     * Creates new form Login
     */
    public Login() {
        // <editor-fold defaultstate="collapsed" desc="Interface de la fenetre">
        initComponents();
        this.setTitle("Paneau d'administation");
        this.setSize(525,430);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        CO.getConnection();
        // </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        Ndc = new javax.swing.JLabel();
        Mdp = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Image = new javax.swing.JLabel();
        Ndc_text = new javax.swing.JTextField();
        PanneauAdmin = new javax.swing.JLabel();
        Mdp_text = new javax.swing.JPasswordField();
        cadre = new javax.swing.JLabel();
        avions = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        Quitte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cadre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 200, 240, 2);

        img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo.png")); // NOI18N
        getContentPane().add(img);
        img.setBounds(20, 100, 240, 80);

        Ndc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ndc.setText("Nom de compte :");
        getContentPane().add(Ndc);
        Ndc.setBounds(40, 230, 120, 20);

        Mdp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mdp.setText("Mot de passe :");
        getContentPane().add(Mdp);
        Mdp.setBounds(40, 280, 100, 20);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(30, 330, 110, 23);

        Image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Documents\\NetBeansProjects\\Avions\\src\\avions\\login.png")); // NOI18N
        getContentPane().add(Image);
        Image.setBounds(250, 100, 240, 270);

        Ndc_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ndc_textActionPerformed(evt);
            }
        });
        getContentPane().add(Ndc_text);
        Ndc_text.setBounds(160, 230, 80, 20);

        PanneauAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanneauAdmin.setText("Panneau d'administration");
        getContentPane().add(PanneauAdmin);
        PanneauAdmin.setBounds(170, 50, 170, 20);
        getContentPane().add(Mdp_text);
        Mdp_text.setBounds(160, 280, 80, 20);

        cadre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cadre);
        cadre.setBounds(270, 90, 220, 280);

        avions.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo-avion.png")); // NOI18N
        getContentPane().add(avions);
        avions.setBounds(0, -10, 90, 100);

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setText("Trip Report : Gestion des retards");
        getContentPane().add(titre);
        titre.setBounds(100, 0, 430, 50);

        Quitte.setText("Quitter");
        Quitte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitteActionPerformed(evt);
            }
        });
        getContentPane().add(Quitte);
        Quitte.setBounds(150, 330, 100, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 78, 550, 2);

        cadre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cadre2);
        cadre2.setBounds(20, 90, 240, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
       
        // <editor-fold defaultstate="collapsed" desc="Récupération du compte administrateur">
        try {
            String nom=Ndc_text.getText();
            String mot=Mdp_text.getText();
            String veri=new String();
            String nomdecompte=new String();
            String motdepasse=new String();
PreparedStatement ndc=CO.com.prepareStatement("SELECT ndc FROM admin");
ResultSet ndc1=ndc.executeQuery();
PreparedStatement mdp=CO.com.prepareStatement("SELECT mdp FROM admin");
ResultSet mdp1=mdp.executeQuery();
while (ndc1.next() && mdp1.next() && veri!="ok"){
                int i=1;
                nomdecompte=ndc1.getObject(i).toString();
                motdepasse=mdp1.getObject(i).toString();
                if (nom.equals(nomdecompte) && (mot.equals(motdepasse))){
                    veri = "ok";
                }
                System.out.println(veri);
                i++;
             }
                if (veri!="ok") {
                    JOptionPane jo1;
                    jo1=new JOptionPane();
                    jo1.showMessageDialog(null,"Mauvais nom de compte ou mot de passe.","ERREUR",JOptionPane.ERROR_MESSAGE);
                }
                else {
                    id ndc11 = new id(Ndc_text.getText());
                    this.dispose();
                    new Accueil().setVisible(true);
                }
} catch (Exception e) {
e.printStackTrace();
}      
        // </editor-fold>
        
    }//GEN-LAST:event_ValiderActionPerformed

    private void Ndc_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ndc_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ndc_textActionPerformed

    private void QuitteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitteActionPerformed
        this.dispose();
    }//GEN-LAST:event_QuitteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Mdp;
    private javax.swing.JPasswordField Mdp_text;
    private javax.swing.JLabel Ndc;
    private javax.swing.JTextField Ndc_text;
    private javax.swing.JLabel PanneauAdmin;
    private javax.swing.JButton Quitte;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel avions;
    private javax.swing.JLabel cadre;
    private javax.swing.JLabel cadre2;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
