/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avions;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.text.SimpleDateFormat;

/**
 *
 * @author Moussa
 */
public class Mouvement extends javax.swing.JFrame {

    /**
     * Creates new form Mouvement
     */
    public Mouvement() {
        
        // <editor-fold defaultstate="collapsed" desc="Interface de la fenetre"> 
         initComponents();
         this.setTitle("Gestion des retards");
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setSize(670,530);
         nomAdmin.setText("Administrateur ["+id.getNdc()+"]");
         nomAdmin.setHorizontalAlignment(SwingConstants.CENTER);
         nomAdmin.setForeground(new java.awt.Color(102, 0, 0));
         PrenomP.setHorizontalAlignment(SwingConstants.CENTER);
         PrenomCP.setHorizontalAlignment(SwingConstants.CENTER);
         PrenomP.setEditable(false);
         PrenomCP.setEditable(false);
         AutreRaisons.setVisible(false);
         // </editor-fold>
         
        // <editor-fold defaultstate="collapsed" desc="Récupère les modeles"> 
   try {

Statement state1 = CO.com.createStatement();
ResultSet resultP = state1.executeQuery("SELECT DISTINCT modele FROM avion");
while(resultP.next()){
    modele.addItem(resultP.getString(1));
}

resultP.close();
state1.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold> 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomAdmin = new javax.swing.JLabel();
        Vol = new javax.swing.JLabel();
        Avion = new javax.swing.JLabel();
        Depart = new javax.swing.JLabel();
        Arrivee = new javax.swing.JLabel();
        jAvion = new javax.swing.JTextField();
        depart = new javax.swing.JSpinner();
        arriver = new javax.swing.JSpinner();
        jRapport = new javax.swing.JButton();
        jAnnuler = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        avionRet = new javax.swing.JLabel();
        tRetard = new javax.swing.JLabel();
        retard = new javax.swing.JSpinner();
        Séparateur = new javax.swing.JSeparator();
        modele = new javax.swing.JComboBox();
        image2 = new javax.swing.JLabel();
        tPilote = new javax.swing.JLabel();
        tCoPilote = new javax.swing.JLabel();
        NomP = new javax.swing.JComboBox();
        NomCP = new javax.swing.JComboBox();
        Trait6 = new javax.swing.JLabel();
        tMinutes = new javax.swing.JLabel();
        Trait5 = new javax.swing.JLabel();
        Titre4 = new javax.swing.JLabel();
        tRetardType = new javax.swing.JLabel();
        AutreRaisons = new javax.swing.JPanel();
        AutresRaisons = new javax.swing.JTextField();
        tOther = new javax.swing.JLabel();
        TypeRetardBox = new javax.swing.JComboBox();
        Cadre2 = new javax.swing.JLabel();
        Cadr4 = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();
        Cadre3 = new javax.swing.JLabel();
        PrenomP = new javax.swing.JTextField();
        PrenomCP = new javax.swing.JTextField();
        idPilote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nomAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 180, 20));

        Vol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vol.setText("Modèle :");
        getContentPane().add(Vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Avion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Avion.setText("N°Vol :");
        getContentPane().add(Avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, 40));

        Depart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Depart.setText("Départ :");
        getContentPane().add(Depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 70, 30));

        Arrivee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Arrivee.setText("Arrivée :");
        getContentPane().add(Arrivee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 60, 30));

        jAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvionActionPerformed(evt);
            }
        });
        getContentPane().add(jAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 40, 20));

        depart.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        getContentPane().add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 30));

        arriver.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        getContentPane().add(arriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 30));

        jRapport.setText("Continuer");
        jRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRapportActionPerformed(evt);
            }
        });
        getContentPane().add(jRapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 30));

        jAnnuler.setText("Retour");
        jAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(jAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 100, 30));

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo-avion.png")); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 70));

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setText("Trip Report : Gestion des retards");
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 420, 30));

        avionRet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avionRet.setText("Informations sur l'avion en retard");
        getContentPane().add(avionRet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 230, 20));

        tRetard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tRetard.setText("Retard :");
        getContentPane().add(tRetard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 70, 30));

        retard.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(15), Integer.valueOf(15), null, Integer.valueOf(15)));
        getContentPane().add(retard, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 40, 30));
        getContentPane().add(Séparateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 710, -1));

        modele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeleActionPerformed(evt);
            }
        });
        getContentPane().add(modele, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 30));

        image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo-avion2.png")); // NOI18N
        getContentPane().add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 210, 170));

        tPilote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tPilote.setText("Pilote :");
        getContentPane().add(tPilote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 20));

        tCoPilote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCoPilote.setText("Co-pilote :");
        getContentPane().add(tCoPilote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        NomP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NomPFocusLost(evt);
            }
        });
        NomP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomPMouseClicked(evt);
            }
        });
        NomP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomPActionPerformed(evt);
            }
        });
        getContentPane().add(NomP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 30));

        NomCP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NomCPItemStateChanged(evt);
            }
        });
        NomCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NomCPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NomCPFocusLost(evt);
            }
        });
        NomCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomCPMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NomCPMouseReleased(evt);
            }
        });
        NomCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomCPActionPerformed(evt);
            }
        });
        getContentPane().add(NomCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, 30));

        Trait6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Trait6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, 210));

        tMinutes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tMinutes.setText("minutes");
        getContentPane().add(tMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 50, 30));

        Trait5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Trait5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 238, 240, -1));

        Titre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Titre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 418, 240, -1));

        tRetardType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tRetardType.setText("Raison du retard :");
        getContentPane().add(tRetardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 130, 30));

        AutreRaisons.setLayout(null);
        AutreRaisons.add(AutresRaisons);
        AutresRaisons.setBounds(10, 40, 110, 20);

        tOther.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tOther.setText("Autre(s) raison(s) :");
        AutreRaisons.add(tOther);
        tOther.setBounds(6, 10, 120, 20);

        getContentPane().add(AutreRaisons, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 130, 80));

        TypeRetardBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Problème de sécurité", "Mauvaise météo", "Passagers perturbateurs", "Grève du personnel", "Verification de l'appareil", "Tour de contrôle injoignable", "Autre(s)" }));
        TypeRetardBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TypeRetardBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(TypeRetardBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 130, 30));

        Cadre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cadre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 350, 210));

        Cadr4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cadr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 150));

        Img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo.png")); // NOI18N
        getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 260, 110));

        Cadre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cadre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 240, 370));

        PrenomP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(PrenomP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, 30));

        PrenomCP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(PrenomCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 30));
        getContentPane().add(idPilote, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAvionActionPerformed

    private void jAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnulerActionPerformed
        this.dispose();
        new Accueil().setVisible(true);
    }//GEN-LAST:event_jAnnulerActionPerformed

    private void jRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRapportActionPerformed
          
        // <editor-fold defaultstate="collapsed" desc="Initialisation des variables">
        SimpleDateFormat formater = new SimpleDateFormat("HH:mm dd/MM");
        String Depart = formater.format(depart.getValue());
        String Arrive = formater.format(arriver.getValue());
        String Modele = modele.getSelectedItem().toString();
        String Pilote = ""+NomP.getSelectedItem().toString()+" "+PrenomP.getText();
        String NomPilote = NomP.getSelectedItem().toString();
        String PrenomPilote = PrenomP.getText();
        String CoPilote = ""+NomCP.getSelectedItem().toString()+" "+PrenomCP.getText();
        String NumeroVol = jAvion.getText();
        int minutesRetard = ((Integer)retard.getValue());
        String MinutesRetard = ""+minutesRetard;
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Veriication du numéro de vol"> 
        String volAvion = "YES";
        if (jAvion.getText().isEmpty()) {
                   volAvion = "NO";
        }       
        else {
            volAvion = "YES";
        }
        
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Verification de la date départ/arrivé">
        String verifDate = "YES";
        if (Depart.equals(Arrive)) {
            verifDate = "NO";
        }
            else {
                verifDate = "YES";
            }
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Verification des raisons">
        String verifRetard = "YES";
        String RetardText = "";
        String Retard = TypeRetardBox.getSelectedItem().toString();
        if (Retard == "Autre(s)") {
            RetardText = AutresRaisons.getText();
            if (RetardText.isEmpty()) {
                verifRetard = "NO";
            }
            else {
                verifRetard = "YES";
            }
        }
        else {
            RetardText = TypeRetardBox.getSelectedItem().toString();
        }
        if (verifRetard == "NO" || volAvion == "NO" || verifDate == "NO" ) {
            if (verifRetard == "NO") {
                JOptionPane.showMessageDialog(null, "Raison du retard vide", "Petit problème !", JOptionPane.ERROR_MESSAGE);
            }
            if (volAvion == "NO") {
                JOptionPane.showMessageDialog(null, "Numéro de vol vide", "Petit problème !", JOptionPane.ERROR_MESSAGE);
            }
            if (verifDate == "NO") {
                JOptionPane.showMessageDialog(null, "La date de départ et d'arrivé du vol ne peut pas être identique", "Petit problème !", JOptionPane.ERROR_MESSAGE);
            }
        }
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Ajout des informations dans la classe InfosRetard et ouverture du rapport">
        else {
                
        // <editor-fold defaultstate="collapsed" desc="Récupère l'ID"> 
   try {

Statement state1 = CO.com.createStatement();
ResultSet resultP = state1.executeQuery("SELECT idPilote FROM pilote WHERE nomPilote='"+NomPilote+"' AND prenomPilote='"+PrenomPilote+"'");
while(resultP.next()){
    idPilote.setText(resultP.getString(1));
}

resultP.close();
state1.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold> 
            String IdPilote = idPilote.getText();
            InfosRetard Modele1, Pilote1, CoPilote1, NumeroVol1,  Depart1, Arrive1, Retard1, RaisonRetard1, idPilote1 = 
        new InfosRetard(Modele, Pilote, CoPilote, NumeroVol, Depart, Arrive, MinutesRetard, RetardText, IdPilote);
            this.dispose();
            new RecapRetard().setVisible(true);
        }
        // </editor-fold>
        
    }//GEN-LAST:event_jRapportActionPerformed

    private void NomPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomPActionPerformed
    
    }//GEN-LAST:event_NomPActionPerformed

    private void modeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeleActionPerformed
         
        // <editor-fold defaultstate="collapsed" desc="Initialisation des variales">
        String Modele = modele.getSelectedItem().toString();
        NomP.removeAllItems();
        NomCP.removeAllItems();
        PrenomP.setText("");
        PrenomCP.setText("");
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Récupère les modeles"> 
   try {
Statement state1 = CO.com.createStatement();
ResultSet resultP = state1.executeQuery("SELECT nomPilote FROM pilote, avion WHERE modele='"+Modele+"' AND pilote.idPilote=avion.idPilote");
Statement state2 = CO.com.createStatement();
ResultSet resultCP = state2.executeQuery("SELECT nomCoPilote FROM copilote, avion WHERE modele='"+Modele+"' AND copilote.idCoPilote=avion.idCoPilote");
while(resultP.next()){
    NomP.addItem(resultP.getString(1)); 
}
while(resultCP.next()){
    NomCP.addItem(resultCP.getString(1));
   
}

resultP.close();
state1.close();
resultCP.close();
state2.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold> 
   
        // <editor-fold defaultstate="collapsed" desc="Récupère les PRENOMS"> 
        
      
   try {
//PrenomP.removeAllItems();
String NomPilote1 = NomP.getSelectedItem().toString();
Statement state3 = CO.com.createStatement();
ResultSet resultP = state3.executeQuery("SELECT prenomPilote FROM pilote WHERE nomPilote='"+NomPilote1+"'");
while(resultP.next()){
    PrenomP.setText(resultP.getString(1));
}

resultP.close();
state3.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold>        
   
        // <editor-fold defaultstate="collapsed" desc="Récupère les prenoms des co pilotes"> 
        
        
   try {
String NomCoPilote = NomCP.getSelectedItem().toString();
PrenomCP.setText("");
Statement state2 = CO.com.createStatement();
ResultSet resultCP = state2.executeQuery("SELECT prenomCoPilote FROM copilote WHERE nomCoPilote='"+NomCoPilote+"'");
while(resultCP.next()){
    PrenomCP.setText(resultCP.getString(1));
}

resultCP.close();
state2.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold> 
   
    }//GEN-LAST:event_modeleActionPerformed

    private void NomCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomCPActionPerformed

   
    }//GEN-LAST:event_NomCPActionPerformed

    private void NomPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NomPMouseClicked

    private void NomCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomCPMouseClicked
         
   
    }//GEN-LAST:event_NomCPMouseClicked

    private void NomCPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NomCPItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_NomCPItemStateChanged

    private void NomCPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomCPMouseReleased
     
    }//GEN-LAST:event_NomCPMouseReleased

    private void NomCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomCPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NomCPFocusGained

    private void NomCPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomCPFocusLost
         // <editor-fold defaultstate="collapsed" desc="Récupère les prenoms des co pilotes"> 
        
        
   try {
   
String NomCoPilote = NomCP.getSelectedItem().toString();
Statement state2 = CO.com.createStatement();
ResultSet resultCP = state2.executeQuery("SELECT prenomCoPilote FROM copilote WHERE nomCoPilote='"+NomCoPilote+"'");
while(resultCP.next()){
    PrenomCP.setText(resultCP.getString(1));
}

resultCP.close();
state2.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold> 
    }//GEN-LAST:event_NomCPFocusLost

    private void NomPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomPFocusLost
      
        // <editor-fold defaultstate="collapsed" desc="Récupère les prenoms des pilotes"> 
        
        
   try {
   
String NomPilote = NomP.getSelectedItem().toString();
Statement state2 = CO.com.createStatement();
ResultSet resultP = state2.executeQuery("SELECT prenomPilote FROM pilote WHERE nomPilote='"+NomPilote+"'");
while(resultP.next()){
    PrenomP.setText(resultP.getString(1));
}

resultP.close();
state2.close();
   }
   catch (Exception e){
       e.printStackTrace();
   }
    // </editor-fold> 
   
    }//GEN-LAST:event_NomPFocusLost

    private void TypeRetardBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TypeRetardBoxItemStateChanged
        String Retard = TypeRetardBox.getSelectedItem().toString();
        if (Retard == "Autre(s)") {
        AutreRaisons.setVisible(true);
    }
        else {
            AutreRaisons.setVisible(false);
        }
    }//GEN-LAST:event_TypeRetardBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mouvement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arrivee;
    private javax.swing.JPanel AutreRaisons;
    private javax.swing.JTextField AutresRaisons;
    private javax.swing.JLabel Avion;
    private javax.swing.JLabel Cadr4;
    private javax.swing.JLabel Cadre2;
    private javax.swing.JLabel Cadre3;
    private javax.swing.JLabel Depart;
    private javax.swing.JLabel Img;
    private javax.swing.JComboBox NomCP;
    private javax.swing.JComboBox NomP;
    private javax.swing.JTextField PrenomCP;
    private javax.swing.JTextField PrenomP;
    private javax.swing.JSeparator Séparateur;
    private javax.swing.JLabel Titre4;
    private javax.swing.JLabel Trait5;
    private javax.swing.JLabel Trait6;
    private javax.swing.JComboBox TypeRetardBox;
    private javax.swing.JLabel Vol;
    private javax.swing.JSpinner arriver;
    private javax.swing.JLabel avionRet;
    private javax.swing.JSpinner depart;
    private javax.swing.JLabel idPilote;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image2;
    private javax.swing.JButton jAnnuler;
    private javax.swing.JTextField jAvion;
    private javax.swing.JButton jRapport;
    private javax.swing.JComboBox modele;
    private javax.swing.JLabel nomAdmin;
    private javax.swing.JSpinner retard;
    private javax.swing.JLabel tCoPilote;
    private javax.swing.JLabel tMinutes;
    private javax.swing.JLabel tOther;
    private javax.swing.JLabel tPilote;
    private javax.swing.JLabel tRetard;
    private javax.swing.JLabel tRetardType;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
