/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avions;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Moussa
 */
public class RecapRetard extends javax.swing.JFrame {

    /**
     * Creates new form Mouvement
     */
    public RecapRetard() {
        
        // <editor-fold defaultstate="collapsed" desc="Interface de la fenetre"> 
         initComponents();
         this.setTitle("Gestion des retards");
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setSize(680,470);
         nomAdmin.setText("Administrateur ["+id.getNdc()+"]");
         nomAdmin.setHorizontalAlignment(SwingConstants.CENTER);
         nomAdmin.setForeground(new java.awt.Color(102, 0, 0));
         Modele.setText(InfosRetard.getModele());
         Modele.setHorizontalAlignment(SwingConstants.CENTER);
         Modele.setForeground(new java.awt.Color(102, 0, 0));
         NomPrenomP.setText(InfosRetard.getPilote());
         NomPrenomP.setHorizontalAlignment(SwingConstants.CENTER);
         NomPrenomP.setForeground(new java.awt.Color(102, 0, 0));
         NomPrenomCP.setText(InfosRetard.getCoPilote());
         NomPrenomCP.setHorizontalAlignment(SwingConstants.CENTER);
         NomPrenomCP.setForeground(new java.awt.Color(102, 0, 0));
         depart.setText(InfosRetard.getDepart());
         depart.setHorizontalAlignment(SwingConstants.CENTER);
         depart.setForeground(new java.awt.Color(102, 0, 0));
         arriver.setText(InfosRetard.getArrive());
         arriver.setHorizontalAlignment(SwingConstants.CENTER);
         arriver.setForeground(new java.awt.Color(102, 0, 0));
         nVol.setText(InfosRetard.getNumeroVol());
         nVol.setHorizontalAlignment(SwingConstants.CENTER);
         nVol.setForeground(new java.awt.Color(102, 0, 0));
         minutesRetard.setText(InfosRetard.getRetard()+" minutes");
         minutesRetard.setHorizontalAlignment(SwingConstants.CENTER);
         minutesRetard.setForeground(new java.awt.Color(102, 0, 0));
         raisonRetard.setText(InfosRetard.getRaisonRetard());
         raisonRetard.setHorizontalAlignment(SwingConstants.CENTER);
         raisonRetard.setForeground(new java.awt.Color(102, 0, 0));
         // </editor-fold>
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomAdmin = new javax.swing.JLabel();
        Vol = new javax.swing.JLabel();
        Avion = new javax.swing.JLabel();
        Depart = new javax.swing.JLabel();
        Arrivee = new javax.swing.JLabel();
        jRapport = new javax.swing.JButton();
        jAnnuler = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        avionRet = new javax.swing.JLabel();
        tRetard = new javax.swing.JLabel();
        Séparateur = new javax.swing.JSeparator();
        image2 = new javax.swing.JLabel();
        tPilote = new javax.swing.JLabel();
        tCoPilote = new javax.swing.JLabel();
        tAeroportA = new javax.swing.JLabel();
        tAeroportD = new javax.swing.JLabel();
        Trait6 = new javax.swing.JLabel();
        Titre4 = new javax.swing.JLabel();
        aeroportD = new javax.swing.JTextField();
        aeroportA = new javax.swing.JTextField();
        tRetardType = new javax.swing.JLabel();
        Cadre2 = new javax.swing.JLabel();
        Cadre3 = new javax.swing.JLabel();
        NomPrenomCP = new javax.swing.JTextField();
        NomPrenomP = new javax.swing.JTextField();
        Modele = new javax.swing.JTextField();
        raisonRetard = new javax.swing.JTextField();
        nVol = new javax.swing.JTextField();
        depart = new javax.swing.JTextField();
        minutesRetard = new javax.swing.JTextField();
        arriver = new javax.swing.JTextField();
        Cadr4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nomAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 20));

        Vol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vol.setText("Modèle :");
        getContentPane().add(Vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 20));

        Avion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Avion.setText("Numéro du Vol :");
        getContentPane().add(Avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 110, 60));

        Depart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Depart.setText("Départ :");
        getContentPane().add(Depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, 40));

        Arrivee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Arrivee.setText("Arrivée :");
        getContentPane().add(Arrivee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 40));

        jRapport.setText("Valider");
        jRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRapportActionPerformed(evt);
            }
        });
        getContentPane().add(jRapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 100, 30));

        jAnnuler.setText("Retour");
        jAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(jAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 90, 30));

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo-avion.png")); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 70));

        titre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titre.setText("Trip Report : Gestion des retards");
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 420, 30));

        avionRet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avionRet.setText("Récapitulatif de l'avion en retard");
        getContentPane().add(avionRet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 230, 20));

        tRetard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tRetard.setText("Minutes de Retard :");
        getContentPane().add(tRetard, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 140, 30));
        getContentPane().add(Séparateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 710, -1));

        image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moussa\\Pictures\\BTS SIO 2\\JAVA\\AVIONS\\logo-avion2.png")); // NOI18N
        getContentPane().add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 210, 170));

        tPilote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tPilote.setText("Pilote :");
        getContentPane().add(tPilote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, 20));

        tCoPilote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCoPilote.setText("Co-pilote :");
        getContentPane().add(tCoPilote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 20));

        tAeroportA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tAeroportA.setText("Aéroport d'arrivé :");
        getContentPane().add(tAeroportA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, 40));

        tAeroportD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tAeroportD.setText("Aéroport de départ :");
        getContentPane().add(tAeroportD, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 310, 160, 40));

        Trait6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Trait6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 210));

        Titre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Titre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 344, 220, -1));
        getContentPane().add(aeroportD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, -1));
        getContentPane().add(aeroportA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 180, -1));

        tRetardType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tRetardType.setText("Raison du retard :");
        getContentPane().add(tRetardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, 30));

        Cadre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cadre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 380, 100));

        Cadre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cadre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 220, 310));

        NomPrenomCP.setEditable(false);
        NomPrenomCP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NomPrenomCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomPrenomCPActionPerformed(evt);
            }
        });
        getContentPane().add(NomPrenomCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 20));

        NomPrenomP.setEditable(false);
        NomPrenomP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(NomPrenomP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, 20));

        Modele.setEditable(false);
        Modele.setBackground(new java.awt.Color(240, 240, 240));
        Modele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Modele, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, 20));

        raisonRetard.setEditable(false);
        raisonRetard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(raisonRetard, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 140, 20));

        nVol.setEditable(false);
        nVol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 50, 20));

        depart.setEditable(false);
        depart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, 20));

        minutesRetard.setEditable(false);
        minutesRetard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        minutesRetard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesRetardActionPerformed(evt);
            }
        });
        getContentPane().add(minutesRetard, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 110, 20));

        arriver.setEditable(false);
        arriver.setBackground(new java.awt.Color(240, 240, 240));
        arriver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(arriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 20));

        Cadr4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cadr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 380, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnulerActionPerformed
        this.dispose();
        new Mouvement().setVisible(true);
    }//GEN-LAST:event_jAnnulerActionPerformed

    private void jRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRapportActionPerformed

        // <editor-fold defaultstate="collapsed" desc="Ajout du vol à la base de données"> 
        if (aeroportD.getText().isEmpty() || aeroportA.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Les aéroports ont été mal saisis", "Petit problème !", JOptionPane.ERROR_MESSAGE);
}
else {
         String ModeleB = Modele.getText();
         String PiloteB = NomPrenomP.getText();
         String CoPiloteB = NomPrenomCP.getText();
         String NumeroVolB = nVol.getText();
         String DateDepartB = depart.getText();
         String DateArriverB = arriver.getText();
         String AeroportDepartB = aeroportD.getText();
         String AeroportArriverB = aeroportA.getText();
         String MinutesRetardB =  minutesRetard.getText();
         String RaisonRetardB = raisonRetard.getText();
         String IdPilote = InfosRetard.getIdPilote();
    try {
          PreparedStatement mouvement =CO.com.prepareStatement("INSERT INTO mouvement (modele, pilote, coPilote, numeroVol, dateHeureDepart, dateHeureArrivee, aeroportDepart, aeroportArriver, retard, raisonRetard)"
                  + " VALUES(('"+ModeleB+"'),"
                  + " ('"+PiloteB+"'),"
                  + " ('"+CoPiloteB+"'),"
                  + " ('"+NumeroVolB+"'),"
                  + " ('"+DateDepartB+"'),"
                  + " ('"+DateArriverB+"'),"
                  + " ('"+AeroportDepartB+"'),"
                  + " ('"+AeroportArriverB+"'),"
                  + " ('"+MinutesRetardB+"'),"
                  + " ('"+RaisonRetardB+"'))");


                mouvement.executeUpdate();
                mouvement.close();
                String nombreRetard = "";
                String Avert = "";
                Statement state1 = CO.com.createStatement();
                ResultSet resultP = state1.executeQuery("SELECT retard FROM pilote WHERE idPilote='"+IdPilote+"'"); 
                while(resultP.next()){
                      nombreRetard = (resultP.getString(1));
                                     }
               
                Statement state2 = CO.com.createStatement();
                ResultSet resultA = state2.executeQuery("SELECT avertissement FROM pilote WHERE idPilote='"+IdPilote+"'");
                while(resultA.next()){
                  Avert = (resultA.getString(1));
                }
                String UnRetard = "1";
                String DeuxRetard = "2";
                String TroisRetard = "3";
                String Avertissement = "Avertissement";
                String Inspection = "Pilote en inspection";
                if (nombreRetard.equals("0")) {
                     PreparedStatement retard1 =CO.com.prepareStatement("UPDATE pilote SET retard='"+UnRetard+"' WHERE idPilote='"+IdPilote+"'");
                     retard1.executeUpdate();
                     retard1.close();
                     JOptionPane.showMessageDialog(null, "Le pilote "+PiloteB+" dispose désormais d'un retard enregistré, au bout de trois retards il recevra un avertissement", "Attention au pilote !", JOptionPane.INFORMATION_MESSAGE);
                     JOptionPane.showMessageDialog(null, "Le retard correspondant au vol "+NumeroVolB+" a bien été enregistré dans la base de données ! Afin de générer un document mail, referez vous à l'accueil.", "Récapitulatif généré", JOptionPane.INFORMATION_MESSAGE);
                     this.dispose();
                     new Accueil().setVisible(true);
                }
                if (nombreRetard.equals("1")) {
                     PreparedStatement retard2 =CO.com.prepareStatement("UPDATE pilote SET retard='"+DeuxRetard+"' WHERE idPilote='"+IdPilote+"'");
                     retard2.executeUpdate();
                     retard2.close();
                     JOptionPane.showMessageDialog(null, "Le pilote "+PiloteB+" dispose désormais de deux retard enregistré, au bout de trois retards il recevra un avertissement", "Attention au pilote !", JOptionPane.INFORMATION_MESSAGE);
                     JOptionPane.showMessageDialog(null, "Le retard correspondant au vol "+NumeroVolB+" a bien été enregistré dans la base de données ! Afin de générer un document mail, referez vous à l'accueil.", "Récapitulatif généré", JOptionPane.INFORMATION_MESSAGE);
                     this.dispose();
                     new Accueil().setVisible(true);
                }
                if (nombreRetard.equals("2")) {
                     PreparedStatement retard3 =CO.com.prepareStatement("UPDATE pilote SET retard='"+TroisRetard+"' WHERE idPilote='"+IdPilote+"'");
                     PreparedStatement avertissement =CO.com.prepareStatement("UPDATE pilote SET avertissement='"+Avertissement+"' WHERE idPilote='"+IdPilote+"'");
                     retard3.executeUpdate();
                     avertissement.executeUpdate();
                     retard3.close();
                     avertissement.close();
                     JOptionPane.showMessageDialog(null, "Le pilote "+PiloteB+" est désormais avertit. Au prochain retard, une enquête interne sera ouverte.", "Attention au pilote !", JOptionPane.INFORMATION_MESSAGE);
                     JOptionPane.showMessageDialog(null, "Le retard correspondant au vol "+NumeroVolB+" a bien été enregistré dans la base de données ! Afin de générer un document mail, referez vous à l'accueil.", "Récapitulatif généré", JOptionPane.INFORMATION_MESSAGE);
                     this.dispose();
                     new Accueil().setVisible(true);
                }
                if (Avert.equals("Avertissement")) {
                    JOptionPane.showMessageDialog(null, "Le pilote "+PiloteB+" se fera désormais inspecter afin de verifier si les retards sont issus d'un cas de force majeur.", "Retrait du permis !", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, "Le retard correspondant au vol "+NumeroVolB+" a bien été enregistré dans la base de données ! Afin de générer un document mail, referez vous à l'accueil.", "Récapitulatif généré", JOptionPane.INFORMATION_MESSAGE);
                    PreparedStatement inspection =CO.com.prepareStatement("UPDATE pilote SET avertissement='"+Inspection+"' WHERE idPilote='"+IdPilote+"'");
                    inspection.executeUpdate();
                    inspection.close();
                    this.dispose();
                    new Accueil().setVisible(true);
                }
                                            }
    catch (SQLException e) {
        e.printStackTrace();
    }
}
        // </editor-fold>
        
    }//GEN-LAST:event_jRapportActionPerformed

    private void NomPrenomCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomPrenomCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomPrenomCPActionPerformed

    private void minutesRetardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesRetardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutesRetardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecapRetard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecapRetard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecapRetard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecapRetard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecapRetard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arrivee;
    private javax.swing.JLabel Avion;
    private javax.swing.JLabel Cadr4;
    private javax.swing.JLabel Cadre2;
    private javax.swing.JLabel Cadre3;
    private javax.swing.JLabel Depart;
    private javax.swing.JTextField Modele;
    private javax.swing.JTextField NomPrenomCP;
    private javax.swing.JTextField NomPrenomP;
    private javax.swing.JSeparator Séparateur;
    private javax.swing.JLabel Titre4;
    private javax.swing.JLabel Trait6;
    private javax.swing.JLabel Vol;
    private javax.swing.JTextField aeroportA;
    private javax.swing.JTextField aeroportD;
    private javax.swing.JTextField arriver;
    private javax.swing.JLabel avionRet;
    private javax.swing.JTextField depart;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image2;
    private javax.swing.JButton jAnnuler;
    private javax.swing.JButton jRapport;
    private javax.swing.JTextField minutesRetard;
    private javax.swing.JTextField nVol;
    private javax.swing.JLabel nomAdmin;
    private javax.swing.JTextField raisonRetard;
    private javax.swing.JLabel tAeroportA;
    private javax.swing.JLabel tAeroportD;
    private javax.swing.JLabel tCoPilote;
    private javax.swing.JLabel tPilote;
    private javax.swing.JLabel tRetard;
    private javax.swing.JLabel tRetardType;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
